version: "3.7"
services:
  mysql_master:
    container_name: mysql_master
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
  mysql_slave:
    container_name: mysql_slave
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
  observer:
    container_name: observer
    build:
      context: .
      dockerfile: ./Dockerfile-observer
    volumes:
      - "./:/root/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: sleep 99999
