FROM ubuntu

RUN apt-get update && apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common \
      mysql-client
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN echo "deb https://download.docker.com/linux/ubuntu bionic stable" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y docker-ce-cli
