FROM ubuntu

RUN apt-get update && apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common \
      mysql-client \
      tmux \
      ruby-full

RUN gem install tmuxinator

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN echo "deb https://download.docker.com/linux/ubuntu bionic stable" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y docker-ce-cli

RUN curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

ENV EDITOR='vim'
ENV SHELL='ash'
